import {
  ArrowDown,
  ArrowDown10,
  ArrowDownZA,
  ArrowRight,
  ArrowUp,
  ArrowUp01,
  ArrowUpAZ,
  BookUser,
  BriefcaseBusiness,
  Building,
  CalendarArrowDown,
  CalendarArrowUp,
  Check,
  Copy,
  CornerDownRight,
  Dot,
  Globe,
  Laptop,
  Loader2,
  LogOut,
  Moon,
  Settings,
  Sun,
  User,
  UserCog,
} from "lucide-react"

export const Icons = {
  Admin: Settings,
  ArrowRight,
  Check,
  Clubs: Building,
  Copy,
  CornerDownRight,
  Deals: BriefcaseBusiness,
  Dot,
  ThemeDark: Moon,
  ThemeLight: Sun,
  ThemeSystem: Laptop,
  Loader: Loader2,
  LogOut,
  Market: Globe,
  Players: BookUser,
  Settings,
  SortAsc: ArrowUp,
  SortDesc: ArrowDown,
  SortDateAsc: CalendarArrowUp,
  SortDateDesc: CalendarArrowDown,
  SortNumberAsc: ArrowUp01,
  SortNumberDesc: ArrowDown10,
  SortTextAsc: ArrowUpAZ,
  SortTextDesc: ArrowDownZA,
  User,
  UserSettings: UserCog,
}

export type Icon = (typeof Icons)[keyof typeof Icons]
export type IconKey = keyof typeof Icons
